version: '2'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loader-web-dev
    environment:
      ENV: develop
    volumes:
      - .:/app
    ports:
      - "170:9000"
    restart: on-failure